GET http://localhost:3003/api/blogs/
###
POST http://localhost:3003/api/blogs/6400ee79572fb6af41e6dce5/comments
content-type: application/json

{
    "comment": "Love this!"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "password"
}
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZWZhZGYwODk4YjYzZTU2ZWI0MGFhZiIsImlhdCI6MTY3NjY1MzE2Mn0._lSJXQcHkTyhuN9HWJRJQIghDch8QjBlm2AIuJTkh6I

{
    "title": "newNewBlog",
    "author": "Rwerqwera",
    "url": "bingbong.org",
    "likes": "0",
    "userId": "63debca86fec14d0c2df3c7b"
}
###
DELETE http://localhost:3003/api/blogs/63e01c39e8cbcde3305f3f24/ HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hcnB1cyIsImlkIjoiNjNlMDExMzhlZDUwOGZlOGZiNDA2NWYzIiwiaWF0IjoxNjc1NjMxOTk4fQ.YIkIgxZfbuDxM4IB06Vg7b8BOfjAsjY2q-2Gx99vcu8
###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "sernup",
    "name": "Beebis",
    "password": "awer"
}
###
PUT http://localhost:3003/api/blogs/63debcdcdcf71643b1eb10db HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hcnB1cyIsImlkIjoiNjNlMDExMzhlZDUwOGZlOGZiNDA2NWYzIiwiaWF0IjoxNjc1NjI4ODcxfQ.MuqxPBfa8D1hAmqKzpGRJjswvg5eNTQx_HeVdEcKHI4

{
    "title": "sample",
    "author": "Johnny Test",
    "url": "google.com/aersers",
    "likes": 2,
    "user": "63debca86fec14d0c2df3c7b"
}
